# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2253e72d1f2ea63ad6f4900e62a51c937bb472894f55a8aefba000e70f87feaa8147e33cc1f9976eb995746e31e9de732b5441dcdb442592244bbccd46dfc5

test:
  secret_key_base: 787c46bc1dad6a264618d42f354c017ed2129981f26bf16cacb388458e042cfddf8501af874be5cbb38df9e08b723e4d2dc7f4f5ca815a4073c6e408b597aff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
